/**
 * gateway/src/middleware/requestLogger.js
 *
 * HTTP request/response logger for the API Gateway.
 *
 * Design decisions:
 * ─────────────────
 * - Uses Morgan for automatic HTTP request logging piped into our
 *   shared Winston logger. This keeps format consistent with every
 *   other service in the monorepo.
 *
 * - Custom token `:correlationId` is added to Morgan so the correlation
 *   ID generated by the correlationId middleware is included in every
 *   log line. This is essential for distributed tracing — you can grep
 *   the correlation ID across all service logs to reconstruct a request.
 *
 * - Custom token `:serviceName` tags the log line with 'gateway' so
 *   log aggregation tools (ELK, Loki) can filter by service easily.
 *
 * - We log to Winston rather than stdout directly so that in production
 *   the output format switches to JSON for machine parsing.
 */

'use strict';

const morgan = require('morgan');
const { createServiceLogger } = require('../../../../shared/utils/logger');

const logger = createServiceLogger('gateway');

// ── Custom Morgan tokens ──────────────────────────────────────────────────────

/**
 * :correlationId  – the X-Correlation-ID attached by correlationId middleware
 */
morgan.token('correlationId', (req) => req.correlationId || '-');

/**
 * :serviceName  – always 'gateway' for filtering in log aggregators
 */
morgan.token('serviceName', () => 'gateway');

/**
 * :userId  – user ID from the decoded JWT token (undefined for public routes)
 */
morgan.token('userId', (req) => (req.user && req.user.userId) || '-');

// ── Format string ─────────────────────────────────────────────────────────────
// Log format:
//   [correlationId] METHOD URL STATUS response_time ms – userId
const FORMAT =
  '[:correlationId] :method :url :status :response-time ms - :userId';

/**
 * requestLogger – Morgan middleware instance configured to pipe into Winston.
 *
 * In development it outputs the custom single-line format above.
 * In production the stream writes to Winston which outputs JSON.
 */
const requestLogger = morgan(FORMAT, {
  stream: {
    write: (message) => logger.http(message.trim()),
  },
  // Skip logging health-check requests to reduce noise
  skip: (req) => req.path === '/health',
});

module.exports = { requestLogger };
